/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#1D4ED8',
        'surface-bg': '#F5F7FB',
        'surface-card': '#FFFFFF',
        'border-default': '#E2E8F0',
        'border-hover': '#CBD5E1',
        'border-focus': '#1D4ED8',
        'text-primary': '#0F172A',
        'text-secondary': '#475569',
        'text-muted': '#64748B',
        'status-ok-fg': '#15803D',
        'status-ok-bg': '#DCFCE7',
        'status-ok-border': '#86EFAC',
        'status-missing-fg': '#B91C1C',
        'status-missing-bg': '#FEE2E2',
        'status-missing-border': '#FCA5A5',
        'status-expired-fg': '#7F1D1D',
        'status-expired-bg': '#FECACA',
        'status-expired-border': '#F87171',
        'status-date-needed-fg': '#92400E',
        'status-date-needed-bg': '#FEF3C7',
        'status-date-needed-border': '#FCD34D',
        'status-not-provided-fg': '#475569',
        'status-not-provided-bg': '#E2E8F0',
        'status-not-provided-border': '#CBD5E1',
        'status-duplicate-fg': '#9A3412',
        'status-duplicate-bg': '#FFEDD5',
        'status-duplicate-border': '#FDBA74',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        bengali: ['"Noto Sans Bengali"', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        gutter: '1.5rem',
        margin: '2rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
      },
      boxShadow: {
        card: '0 1px 3px 0 rgba(15, 23, 42, 0.05), 0 1px 2px -1px rgba(15, 23, 42, 0.05)',
        raised: '0 4px 6px -1px rgba(15, 23, 42, 0.07), 0 2px 4px -2px rgba(15, 23, 42, 0.05)',
        action: '0 -4px 12px 0 rgba(15, 23, 42, 0.08)',
      },
      typography: {
        'display-title': {
          fontSize: '28px',
          lineHeight: '36px',
          fontWeight: '700',
          letterSpacing: '-0.02em',
        },
        'headline-section': {
          fontSize: '20px',
          lineHeight: '28px',
          fontWeight: '600',
          letterSpacing: '-0.01em',
        },
      },
    },
  },
  plugins: [],
}
